server:
   port: 8088
mybatis:
  config-location: classpath:mybatis-config.xml
app:
  datasource:
    livtrip:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.89.193.4:3306/livtrip?useSSL=false
      username: livtrip
      password: livtrip#A2016
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
spring:
    aop:
      auto: true
      proxy-target-class: false
    mail:
        host: smtp.163.com
        username: livtrip@163.com
        password: livtrip2017
        properties:
               mail:
                 smtp:
                   auth: true
                   starttls:
                      enable: true
                      required: true
