server:
   port: 8080
mybatis:
  config-location: classpath:mybatis-config.xml
app:
  datasource:
    livtrip:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.89.193.4:3306/livtrip?useSSL=false
      username: livtrip
      password: livtrip#A2016
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
spring:
    aop:
      auto: true
      proxy-target-class: false
    mail:
        host: smtp.163.com
        username: livtrip@163.com
        password: livtrip2017
        properties:
               mail:
                 smtp:
                   auth: true
                   starttls:
                      enable: true
                      required: true
pay:
  alipay:
     appId: 2017071907811942
     privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDd8TKdSidc39+h1v3U2BmfvvbK0/GtrB7hf6UD28nzTQZbSYlEebKphKKj3DUv1pqXIhaE0mrcRKpeZDEFJeroLUDfUNAHiDNZj8jMboqbh9ZaQzHjSQpv2EzUvT3G6Ivj8TboOP0G8gCZQi4Ii9JS3u1XbdpOLVyRwbutAu5CfzSHVRpe0Jb/HJfQznoln2+UOlE+0EoII4bM5p8mGQFwDN+zXPQsIKCzLGTdLzFff9EU7KToBqQLXGyOnOzni/X4ypvLHIkp9YxqB1AXroG5u4kwGpTrjfbJoluEVXuJdLc/CsecW9HYBM4b8Qhm7sqkHJWrJ4HfS5V42XA1TCuJAgMBAAECggEAJZVkttIJ3GZk3mkjztlRbYXPEQXXFUviZtlQvliH2FWgz/Ch+CCLqr01NX5i21kCELnLCm7/fZF7METTMEX9g5e2Nprev4fG+lGo9UV631+fYuWiGxURWWNNj3EEdxyGI/GDFMwhvP1aMJnOZdAXq8ToeDe4EikIVf5yo5etdUD4f4Zwgc0RkVvvyZnHdJAmU8j6BGL9S0nO9uGyaXFM/cJdQN/4naLWwnWGlcwf4ZnPgrR3AAt7pubgIiOpLRv1zOlFQts+5eqQOfeuesRNPV8ob4LfU+MrINGsl+o6t1tWXs+ObCJr30m5zi+snk1g8uAS02NE4K4IC+qzhFXKAQKBgQD34Qr8KM0ZehKNgW5WJ0HdULeEapEY/mkYJHZBzuLsvHR1K+qtVd5ewMoffjOiqG8CPfU/uHeIH/Us9XEdTH15E84e+jEhM8PDb4meBQTQ24esy9YhlCFpfhnicEoM0Zxp9+2j/m4w8HlAfEqZOi9lINRm77mkBQnZjAvx6sRloQKBgQDlNp9fq5Lv1LmOLEb5FKhVsNHJbgks7PYIOT1bMTP+q8Rzfyj7F9/jzXhAxfA3QCNf397zaBAEA1W9Vl+LH9n3ROAExXduBk7M4z3KAZ8In4r3mHYeNLgwYW2usiyuTQrfGvcA7lIzkpMj4rIKpf0wFVHsfto68/qT+UmzRpQs6QKBgDcS4B7wbcloTvDzvfEUXdTvVybrint0IyODDmdGsTKKGJHkBQsoFfUVfpMKtixAohFsdK4IrT4oY4/upIgu833QQa6uRfYriyZEBN6AHPbOn9FrpJLnV5kZtGSUME+yzr7YoAscv5zOARKryuNKgzdD2Q1Z2/QuTmbwb8L7N1GhAoGBAI5VNPI7oKq89dyLMidJ5J4RhrQGWDxFiSHiKW+PRjJGh18Q/2mskaLr3FickWY9tbm7Ur7jR862I2/HSt0hkkAxzMoptNflotkn4x6lkxPPvoOxcOeg5R9l4K4yhfxWawHPxMIXO4Q66JPIGbbzDB3nn0+0Fd+10UxB6LoigbDBAoGBAOMi/rWWd6J8evj2ZfLdKuKiJwq4lDlhrC8z3ViOiyIDP57d4WUNQI9lPjo11Yj6sZtTVS2krJeK7y0HeS6RVFhVJIOo2riXLWZQdMmoDT1wLYeSnk+nF6MwpehpilNNVBsXwqpzSiMzCmf0Ddm9GvzMJftY1tePxZCqXGUOQ/ex
     alipayPulicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3fEynUonXN/fodb91NgZn772ytPxrawe4X+lA9vJ800GW0mJRHmyqYSio9w1L9aalyIWhNJq3ESqXmQxBSXq6C1A31DQB4gzWY/IzG6Km4fWWkMx40kKb9hM1L09xuiL4/E26Dj9BvIAmUIuCIvSUt7tV23aTi1ckcG7rQLuQn80h1UaXtCW/xyX0M56JZ9vlDpRPtBKCCOGzOafJhkBcAzfs1z0LCCgsyxk3S8xX3/RFOyk6AakC1xsjpzs54v1+MqbyxyJKfWMagdQF66BubuJMBqU6432yaJbhFV7iXS3PwrHnFvR2ATOG/EIZu7KpByVqyeB30uVeNlwNUwriQIDAQAB
     serverUrl: https://openapi.alipay.com/gateway.do
     notifyDomain: http://www.livtrip.com/alipay/notify.do
