mybatis:
  config-location: classpath:mybatis-config.xml
app:
  datasource:
    trbs:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.89.193.4:3306/livtrip?useSSL=false
      username: livtrip
      password: livtrip#A2016
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
spring:
    freemarker:
          allow-request-override: false
          cache: true
          check-template-location: true
          charset: UTF-8
          content-type: text/html
          expose-request-attributes: false
          expose-session-attributes: false
          expose-spring-macro-helpers: false
