server:
   port: 8080
mybatis:
  config-location: classpath:mybatis-config.xml
app:
  datasource:
    livtrip:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.89.193.4:3306/livtrip?useSSL=false
      username: livtrip
      password: livtrip#A2016
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
spring:
    aop:
      auto: true
      proxy-target-class: false
    mail:
        host: smtp.163.com
        username: livtrip@163.com
        password: livtrip2017
        properties:
               mail:
                 smtp:
                   auth: true
                   starttls:
                      enable: true
                      required: true
pay:
  alipay:
     appId: 2017071907811942
     privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFDGu4g/EiBrCPr/Ik2ROdmSdxSp2OCjSgG4/S6sD+dt//oQOZP4FW9Fu1/IDd1pjyz0vJFEm8e1M79rVb7us+aZG7s45rIYPKe7gt+oOsXeKcw+CRR99HytUZug4u/kZIYr63DbAj3H55cLXmATaz/sF/9Egm6jXITxviLjSuEMxqgdAD766lmlJAhOsNk7vusdeGtBwYsA8EhS0xglOFjzehjX6PSe8zVRn01enkC+f/OSpMvl0l8ujI1Cud9sJdSJBlvN4TRuWAKgIk1/ks9tQcm1JCudmxYzMt1umiPJpqmhBdhQGhNugMLcvSOlP5ELOCq+ujurH7oUUE6GCJAgMBAAECggEBAKP3T/O8JvzPYEBQgkfTMpVjigSluDEnoN7R0H4Lxgh41rAaRapRw8idkWr/8COonKD/ieqKrUjfvkUZZ5RWXP4UTqZIJWxT+RyWko3/9W2KujUEcWuyyMMuruC3h3HnOIinUld0Vmug4MUg2tvHisOAa3eTyC5JmfNSkLtHA6MK9REKgZo+utlBhRoJT6MHeqhQT+Z4Mfzh/2atrjeN3emUTlqN16gxRjhYqF/s0knE5bLNtUg01MgiyF75Dy9BQbP5WKZOMKsyxS1JFPJNCLOsm1AT6kMiFaAKfeWjXxpliV+dETvLQXOWBHtT1r7loTwlbI2XckAA1tL4KKZBoXkCgYEA7XEEDduVgaNxAT+0P3YN+Lw0n73TzT0Bc5umlLpwqLBR0fHafbwkq3InwWKeDPPsd5hwoaGOqfWazYvXI3bj5orK4+ZpYB0faJEByCUnIHsQn/0Ot0O/rG94UsJv/4MWdUeatgNmUhNjibOAziOeePvfJAWPdsDttiE5k2613q8CgYEA1HMt7H8yEmHgd+I0ytEgPp8JOGQp8OQ+m9HPhckKczBpcIuBTuQidwSyM4Lv8fAF+sXMlHh6TowoX0diYact9/RGlA904gJ+WZXx8LuV8XyrPQLVQM3HdxbSteg8nYCIyuWo0FqRdySjSfxKQBM3N85g9eBeKxzTp73BddN5wkcCgYEA4NZFyoGFvu5vkYkrO3SkokZFZoYwS4ZbG4fmY6twBqx/rdfg13MTHi3Iq3ygwQ8xecYl0UfUeegSIFUs8W4hPCttGAUU/2hUV4YIM+fKdx1Rjs3n424J0FT1kRiBSWhuGbwmKfhqKYomlTwe2hQsec+3arrBMOhbsD0h8hPBsA0CgYBHf5vtA8GuPhJ1RkPOHiNj79ICkHMtByOq/SmCNO63ZYuWvNx/2Hdg5suyWla2bbkVdIwtS36eAL11k2igxMrLsAIwwiLsDTrIm5YZFoiYBQT8O3/Zl2eRxLSVU9tShneDEVeHB3P9TO9HbwjuF4l11pb7KM+IYuM4iLwbE1je8QKBgEKeGmRvEgcm6+o/IVTziIC96Z5dbMMyJxHCK1WLQa2AFAQTQe0Mz2rsqJH0g0n1OybXI1hhFp6sKBdN1D6oBeU9fp+aJiX5zFLNIQlZtXfZMyafa81dkfwJ4fVdk2I0LBFX8kUHXNx303uFVjSGdX0Uae8bUvfqXWipvi5wlQkc
     alipayPulicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxQxruIPxIgawj6/yJNkTnZkncUqdjgo0oBuP0urA/nbf/6EDmT+BVvRbtfyA3daY8s9LyRRJvHtTO/a1W+7rPmmRu7OOayGDynu4LfqDrF3inMPgkUffR8rVGboOLv5GSGK+tw2wI9x+eXC15gE2s/7Bf/RIJuo1yE8b4i40rhDMaoHQA++upZpSQITrDZO77rHXhrQcGLAPBIUtMYJThY83oY1+j0nvM1UZ9NXp5Avn/zkqTL5dJfLoyNQrnfbCXUiQZbzeE0blgCoCJNf5LPbUHJtSQrnZsWMzLdbpojyaapoQXYUBoTboDC3L0jpT+RCzgqvro7qx+6FFBOhgiQIDAQAB
     serverUrl: https://openapi.alipay.com/gateway.do
     notifyDomain: http://www.livtrip.com/alipay/notify.do
