server:
   port: 8888
mybatis:
  config-location: classpath:mybatis-config.xml
app:
  datasource:
    livtrip:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.89.193.4:3306/livtrip?useSSL=false
      username: livtrip
      password: livtrip#A2016
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
spring:
    aop:
      auto: true
      proxy-target-class: false
    mail:
        host: smtp.163.com
        username: livtrip@163.com
        password: livtrip2017
        properties:
               mail:
                 smtp:
                   auth: true
                   starttls:
                      enable: true
                      required: true
pay:
  alipay:
     appId: 2017011905226071
     privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCCqhRqmG5cA9Z/fKI7KzADnbL2y6LFv4LRpUYTY93pn2l7dKHzguq3FeV/rGJTiSUdA5c25ss/hvRspYQ34YC6QV9WWf+SWXyomU5qzql+M4LfqoohYQpaCv3zUbkC0nuARS9ybxNJObZSz/XrRjb8hp2L8BaQvBT91xIVhF8Ae3eQxuhKwj9OaUa6cqFmmDyRqPnkHVH79MJw+nGYMfNEeif3WmXQWH6h7Y/I/edOIg1uB/EVsuv61aWC6AQfbsnvyN4Pf6k66OUlnWoiZVDDuh4W+hqYAq6WVaDsd0QppyLyHHJjC8uiwNUXBknqq9G3VoKnPHisg9ORjPFWlv1NAgMBAAECggEAEhv2Zmun5/LUOKkSZvbuWaHymsfQUG3heKLaWned2vIwEV8xzukXFLbhLte6bO92CFZmD8Le6ngOyjwKXiBP0gCbcQFaLXNflpJgzubDkO0ct1kQed3ULHSXi7CI3r5DRZzRHaANYTmxbjrKT4hUuJ0DmtB0oCyhEClNpVPKQuulR1wBbxAG8jRR6yp3dwXeENFc2D2SK6H+S0QWyHOZCyxwubE9U+fmKJYEGUpgLdHWbSpKcMoQJZ2c4MGkVA59CrG5HvMRwYPTLhtIjoBXBog+/NkSNUCnZh3yWm9IWmue8lyXlv7BbTqr4qdA5DiEZZR2l0tmxih6np1ZzWdt1QKBgQDuFZxcH8VMu5pHOp8Imj03yYlpKhPV6DiFjSnKdipKvK6LHgBEEXuwbWDy1oXqmUk4MJMbrPY8WKYILFJ+byXtl4jvMwIB2Z+vlRGYJ/5NgAnEqXEyGQlEXOXAYaUDvy07WYPyU2zF1jmicX5q3Wo2EhjDfxI4Q+vGrSZOH4/ExwKBgQCMfykPQJB+RxG8SzH4E4pPT3tCVBwwB44S3AZ74fStGlAjn6jLU+VX9SER4Ea8TJ7EE1tPP6E8c9RIaGkEN6j3mBDtLfBRFzqXDovNMV14toFEOv+QPbsjEJ24VyQiNeJ1ejnNNrQQiaS7Y4TIqO+hR5aF68QNdp9prElQW//xSwKBgQCk7//EqpXq1MTKt8fZE9F5RnuViXr4Y8pUazkac8ZUxGY/JmeUwG/qB7x0Pz3DCrJ45N3k/GwR3nAXlW0I/kNOV/6bh8DKO1OvNhxcRsicNCmQPrqWtFWBMMJSBtNkxxq01Qzd4gGnBQQkj2++5Olh0COru+qJZDSBDQ9Oa/sTnQKBgAYl+nIEbU5ZZdlLoSAuGrtlywsYCzO+4OTKZC4/sSlyIVetwQFE5qB2xb+2hOHwqHIENta8/h1bJEsW5qGcnfRX30XB4OZrkdDSfiO4qVKDCh0mR9DUIsBiFcTfa2Fj4kkp1CW64x5mJ6Nbs4/kdLgmHdw2eRntuwQw2fR+UjEJAoGBAMs7OBSLz2cvnUpYaQF3cPNYZX/5th05Z/bXRJzwnWqocwWFa25XFUYOcJlgaV9ZbURn7FDjFFCfTapSOHssbvyNRuDraQVplHDn99dGRNUQcrY3fQvr2n/ZeIRGaiShHbsMt8SjU5rT19l3DPjY4lqnJ9UQfvHlNdtwPoIfITPC
     alipayPulicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi6zQ0VOoCbA1t828YRtzUqyUXC6rXNK25eWKUcj1TFWXSZ2LSK1rfHHE4zpYVzUreZbBNTF1f3E+saJHO6ZuTnapAAJYLdnXqG5Rjkjt5pUShsp7GG142K3/JPebtCpP+JhnLY81fQHif/ZFBrc4qOtxEE8yKLN6tpEErsPiP/J08Fi3qX91xKUZ6O4GzXXOr7vrcNW1uZ+GNB3WOBNRaViDT8B7h6vkQCyMB9Lt7dYFYxEJAz+cdtHA2BYGj5EFkbzbVx4iRZyESv7HA6vG5sqV2ORb7Ni+sQWFC7Mn/mD1euG8blBf+oGHVufsjHmE6q6Qcgi+Lz8oxlFTXL6NzQIDAQAB
     serverUrl: https://openapi.alipay.com/gateway.do
     notifyDomain: http://www.livtrip.com/alipay/notify.do
