package com.livtrip.web.domain;

import java.util.Date;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.hotel_id
     *
     * @mbg.generated
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.start_level
     *
     * @mbg.generated
     */
    private Double startLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.rooms
     *
     * @mbg.generated
     */
    private Integer rooms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.provider
     *
     * @mbg.generated
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.check_in_time
     *
     * @mbg.generated
     */
    private String checkInTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.check_out_time
     *
     * @mbg.generated
     */
    private String checkOutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.hotel_phone
     *
     * @mbg.generated
     */
    private String hotelPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.hotel_fax
     *
     * @mbg.generated
     */
    private String hotelFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.ranking
     *
     * @mbg.generated
     */
    private String ranking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.flag
     *
     * @mbg.generated
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.update_person
     *
     * @mbg.generated
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_hotel.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.id
     *
     * @return the value of liv_hotel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.id
     *
     * @param id the value for liv_hotel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.product_id
     *
     * @return the value of liv_hotel.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.product_id
     *
     * @param productId the value for liv_hotel.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.hotel_id
     *
     * @return the value of liv_hotel.hotel_id
     *
     * @mbg.generated
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.hotel_id
     *
     * @param hotelId the value for liv_hotel.hotel_id
     *
     * @mbg.generated
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.start_level
     *
     * @return the value of liv_hotel.start_level
     *
     * @mbg.generated
     */
    public Double getStartLevel() {
        return startLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.start_level
     *
     * @param startLevel the value for liv_hotel.start_level
     *
     * @mbg.generated
     */
    public void setStartLevel(Double startLevel) {
        this.startLevel = startLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.rooms
     *
     * @return the value of liv_hotel.rooms
     *
     * @mbg.generated
     */
    public Integer getRooms() {
        return rooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.rooms
     *
     * @param rooms the value for liv_hotel.rooms
     *
     * @mbg.generated
     */
    public void setRooms(Integer rooms) {
        this.rooms = rooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.provider
     *
     * @return the value of liv_hotel.provider
     *
     * @mbg.generated
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.provider
     *
     * @param provider the value for liv_hotel.provider
     *
     * @mbg.generated
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.check_in_time
     *
     * @return the value of liv_hotel.check_in_time
     *
     * @mbg.generated
     */
    public String getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.check_in_time
     *
     * @param checkInTime the value for liv_hotel.check_in_time
     *
     * @mbg.generated
     */
    public void setCheckInTime(String checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.check_out_time
     *
     * @return the value of liv_hotel.check_out_time
     *
     * @mbg.generated
     */
    public String getCheckOutTime() {
        return checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.check_out_time
     *
     * @param checkOutTime the value for liv_hotel.check_out_time
     *
     * @mbg.generated
     */
    public void setCheckOutTime(String checkOutTime) {
        this.checkOutTime = checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.hotel_phone
     *
     * @return the value of liv_hotel.hotel_phone
     *
     * @mbg.generated
     */
    public String getHotelPhone() {
        return hotelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.hotel_phone
     *
     * @param hotelPhone the value for liv_hotel.hotel_phone
     *
     * @mbg.generated
     */
    public void setHotelPhone(String hotelPhone) {
        this.hotelPhone = hotelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.hotel_fax
     *
     * @return the value of liv_hotel.hotel_fax
     *
     * @mbg.generated
     */
    public String getHotelFax() {
        return hotelFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.hotel_fax
     *
     * @param hotelFax the value for liv_hotel.hotel_fax
     *
     * @mbg.generated
     */
    public void setHotelFax(String hotelFax) {
        this.hotelFax = hotelFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.ranking
     *
     * @return the value of liv_hotel.ranking
     *
     * @mbg.generated
     */
    public String getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.ranking
     *
     * @param ranking the value for liv_hotel.ranking
     *
     * @mbg.generated
     */
    public void setRanking(String ranking) {
        this.ranking = ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.flag
     *
     * @return the value of liv_hotel.flag
     *
     * @mbg.generated
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.flag
     *
     * @param flag the value for liv_hotel.flag
     *
     * @mbg.generated
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.create_time
     *
     * @return the value of liv_hotel.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.create_time
     *
     * @param createTime the value for liv_hotel.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.create_person
     *
     * @return the value of liv_hotel.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.create_person
     *
     * @param createPerson the value for liv_hotel.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.update_time
     *
     * @return the value of liv_hotel.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.update_time
     *
     * @param updateTime the value for liv_hotel.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.update_person
     *
     * @return the value of liv_hotel.update_person
     *
     * @mbg.generated
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.update_person
     *
     * @param updatePerson the value for liv_hotel.update_person
     *
     * @mbg.generated
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_hotel.description
     *
     * @return the value of liv_hotel.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_hotel.description
     *
     * @param description the value for liv_hotel.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_hotel
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hotel other = (Hotel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getStartLevel() == null ? other.getStartLevel() == null : this.getStartLevel().equals(other.getStartLevel()))
            && (this.getRooms() == null ? other.getRooms() == null : this.getRooms().equals(other.getRooms()))
            && (this.getProvider() == null ? other.getProvider() == null : this.getProvider().equals(other.getProvider()))
            && (this.getCheckInTime() == null ? other.getCheckInTime() == null : this.getCheckInTime().equals(other.getCheckInTime()))
            && (this.getCheckOutTime() == null ? other.getCheckOutTime() == null : this.getCheckOutTime().equals(other.getCheckOutTime()))
            && (this.getHotelPhone() == null ? other.getHotelPhone() == null : this.getHotelPhone().equals(other.getHotelPhone()))
            && (this.getHotelFax() == null ? other.getHotelFax() == null : this.getHotelFax().equals(other.getHotelFax()))
            && (this.getRanking() == null ? other.getRanking() == null : this.getRanking().equals(other.getRanking()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_hotel
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getStartLevel() == null) ? 0 : getStartLevel().hashCode());
        result = prime * result + ((getRooms() == null) ? 0 : getRooms().hashCode());
        result = prime * result + ((getProvider() == null) ? 0 : getProvider().hashCode());
        result = prime * result + ((getCheckInTime() == null) ? 0 : getCheckInTime().hashCode());
        result = prime * result + ((getCheckOutTime() == null) ? 0 : getCheckOutTime().hashCode());
        result = prime * result + ((getHotelPhone() == null) ? 0 : getHotelPhone().hashCode());
        result = prime * result + ((getHotelFax() == null) ? 0 : getHotelFax().hashCode());
        result = prime * result + ((getRanking() == null) ? 0 : getRanking().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_hotel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", hotelId=").append(hotelId);
        sb.append(", startLevel=").append(startLevel);
        sb.append(", rooms=").append(rooms);
        sb.append(", provider=").append(provider);
        sb.append(", checkInTime=").append(checkInTime);
        sb.append(", checkOutTime=").append(checkOutTime);
        sb.append(", hotelPhone=").append(hotelPhone);
        sb.append(", hotelFax=").append(hotelFax);
        sb.append(", ranking=").append(ranking);
        sb.append(", flag=").append(flag);
        sb.append(", createTime=").append(createTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}