package com.livtrip.web.domain;

import java.util.Date;

public class PaySerial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.serial_no
     *
     * @mbg.generated
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.bill_no
     *
     * @mbg.generated
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.mer_id
     *
     * @mbg.generated
     */
    private String merId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.pay_account
     *
     * @mbg.generated
     */
    private String payAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.return_url
     *
     * @mbg.generated
     */
    private String returnUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.notify_url
     *
     * @mbg.generated
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.retain
     *
     * @mbg.generated
     */
    private String retain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.update_person
     *
     * @mbg.generated
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_pay_serial.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.id
     *
     * @return the value of liv_pay_serial.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.id
     *
     * @param id the value for liv_pay_serial.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.serial_no
     *
     * @return the value of liv_pay_serial.serial_no
     *
     * @mbg.generated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.serial_no
     *
     * @param serialNo the value for liv_pay_serial.serial_no
     *
     * @mbg.generated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.bill_no
     *
     * @return the value of liv_pay_serial.bill_no
     *
     * @mbg.generated
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.bill_no
     *
     * @param billNo the value for liv_pay_serial.bill_no
     *
     * @mbg.generated
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.amount
     *
     * @return the value of liv_pay_serial.amount
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.amount
     *
     * @param amount the value for liv_pay_serial.amount
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.status
     *
     * @return the value of liv_pay_serial.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.status
     *
     * @param status the value for liv_pay_serial.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.mer_id
     *
     * @return the value of liv_pay_serial.mer_id
     *
     * @mbg.generated
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.mer_id
     *
     * @param merId the value for liv_pay_serial.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(String merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.pay_account
     *
     * @return the value of liv_pay_serial.pay_account
     *
     * @mbg.generated
     */
    public String getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.pay_account
     *
     * @param payAccount the value for liv_pay_serial.pay_account
     *
     * @mbg.generated
     */
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.return_url
     *
     * @return the value of liv_pay_serial.return_url
     *
     * @mbg.generated
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.return_url
     *
     * @param returnUrl the value for liv_pay_serial.return_url
     *
     * @mbg.generated
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.notify_url
     *
     * @return the value of liv_pay_serial.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.notify_url
     *
     * @param notifyUrl the value for liv_pay_serial.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.product_code
     *
     * @return the value of liv_pay_serial.product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.product_code
     *
     * @param productCode the value for liv_pay_serial.product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.subject
     *
     * @return the value of liv_pay_serial.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.subject
     *
     * @param subject the value for liv_pay_serial.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.body
     *
     * @return the value of liv_pay_serial.body
     *
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.body
     *
     * @param body the value for liv_pay_serial.body
     *
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.retain
     *
     * @return the value of liv_pay_serial.retain
     *
     * @mbg.generated
     */
    public String getRetain() {
        return retain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.retain
     *
     * @param retain the value for liv_pay_serial.retain
     *
     * @mbg.generated
     */
    public void setRetain(String retain) {
        this.retain = retain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.create_person
     *
     * @return the value of liv_pay_serial.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.create_person
     *
     * @param createPerson the value for liv_pay_serial.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.create_time
     *
     * @return the value of liv_pay_serial.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.create_time
     *
     * @param createTime the value for liv_pay_serial.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.update_person
     *
     * @return the value of liv_pay_serial.update_person
     *
     * @mbg.generated
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.update_person
     *
     * @param updatePerson the value for liv_pay_serial.update_person
     *
     * @mbg.generated
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_pay_serial.update_time
     *
     * @return the value of liv_pay_serial.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_pay_serial.update_time
     *
     * @param updateTime the value for liv_pay_serial.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_pay_serial
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaySerial other = (PaySerial) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSerialNo() == null ? other.getSerialNo() == null : this.getSerialNo().equals(other.getSerialNo()))
            && (this.getBillNo() == null ? other.getBillNo() == null : this.getBillNo().equals(other.getBillNo()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getMerId() == null ? other.getMerId() == null : this.getMerId().equals(other.getMerId()))
            && (this.getPayAccount() == null ? other.getPayAccount() == null : this.getPayAccount().equals(other.getPayAccount()))
            && (this.getReturnUrl() == null ? other.getReturnUrl() == null : this.getReturnUrl().equals(other.getReturnUrl()))
            && (this.getNotifyUrl() == null ? other.getNotifyUrl() == null : this.getNotifyUrl().equals(other.getNotifyUrl()))
            && (this.getProductCode() == null ? other.getProductCode() == null : this.getProductCode().equals(other.getProductCode()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getBody() == null ? other.getBody() == null : this.getBody().equals(other.getBody()))
            && (this.getRetain() == null ? other.getRetain() == null : this.getRetain().equals(other.getRetain()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_pay_serial
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSerialNo() == null) ? 0 : getSerialNo().hashCode());
        result = prime * result + ((getBillNo() == null) ? 0 : getBillNo().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getMerId() == null) ? 0 : getMerId().hashCode());
        result = prime * result + ((getPayAccount() == null) ? 0 : getPayAccount().hashCode());
        result = prime * result + ((getReturnUrl() == null) ? 0 : getReturnUrl().hashCode());
        result = prime * result + ((getNotifyUrl() == null) ? 0 : getNotifyUrl().hashCode());
        result = prime * result + ((getProductCode() == null) ? 0 : getProductCode().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getBody() == null) ? 0 : getBody().hashCode());
        result = prime * result + ((getRetain() == null) ? 0 : getRetain().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_pay_serial
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serialNo=").append(serialNo);
        sb.append(", billNo=").append(billNo);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", merId=").append(merId);
        sb.append(", payAccount=").append(payAccount);
        sb.append(", returnUrl=").append(returnUrl);
        sb.append(", notifyUrl=").append(notifyUrl);
        sb.append(", productCode=").append(productCode);
        sb.append(", subject=").append(subject);
        sb.append(", body=").append(body);
        sb.append(", retain=").append(retain);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}