package com.livtrip.web.domain;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.thumb
     *
     * @mbg.generated
     */
    private String thumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.sale_price
     *
     * @mbg.generated
     */
    private Integer salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.clear_price
     *
     * @mbg.generated
     */
    private Integer clearPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.market_price
     *
     * @mbg.generated
     */
    private Integer marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.vendor
     *
     * @mbg.generated
     */
    private String vendor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.is_best
     *
     * @mbg.generated
     */
    private Byte isBest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.hotel_id
     *
     * @mbg.generated
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liv_product.update_person
     *
     * @mbg.generated
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.id
     *
     * @return the value of liv_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.id
     *
     * @param id the value for liv_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.name
     *
     * @return the value of liv_product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.name
     *
     * @param name the value for liv_product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.type
     *
     * @return the value of liv_product.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.type
     *
     * @param type the value for liv_product.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.thumb
     *
     * @return the value of liv_product.thumb
     *
     * @mbg.generated
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.thumb
     *
     * @param thumb the value for liv_product.thumb
     *
     * @mbg.generated
     */
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.currency
     *
     * @return the value of liv_product.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.currency
     *
     * @param currency the value for liv_product.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.brand_name
     *
     * @return the value of liv_product.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.brand_name
     *
     * @param brandName the value for liv_product.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.keywords
     *
     * @return the value of liv_product.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.keywords
     *
     * @param keywords the value for liv_product.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.description
     *
     * @return the value of liv_product.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.description
     *
     * @param description the value for liv_product.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.sale_price
     *
     * @return the value of liv_product.sale_price
     *
     * @mbg.generated
     */
    public Integer getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.sale_price
     *
     * @param salePrice the value for liv_product.sale_price
     *
     * @mbg.generated
     */
    public void setSalePrice(Integer salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.clear_price
     *
     * @return the value of liv_product.clear_price
     *
     * @mbg.generated
     */
    public Integer getClearPrice() {
        return clearPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.clear_price
     *
     * @param clearPrice the value for liv_product.clear_price
     *
     * @mbg.generated
     */
    public void setClearPrice(Integer clearPrice) {
        this.clearPrice = clearPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.market_price
     *
     * @return the value of liv_product.market_price
     *
     * @mbg.generated
     */
    public Integer getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.market_price
     *
     * @param marketPrice the value for liv_product.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(Integer marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.vendor
     *
     * @return the value of liv_product.vendor
     *
     * @mbg.generated
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.vendor
     *
     * @param vendor the value for liv_product.vendor
     *
     * @mbg.generated
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.is_best
     *
     * @return the value of liv_product.is_best
     *
     * @mbg.generated
     */
    public Byte getIsBest() {
        return isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.is_best
     *
     * @param isBest the value for liv_product.is_best
     *
     * @mbg.generated
     */
    public void setIsBest(Byte isBest) {
        this.isBest = isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.hotel_id
     *
     * @return the value of liv_product.hotel_id
     *
     * @mbg.generated
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.hotel_id
     *
     * @param hotelId the value for liv_product.hotel_id
     *
     * @mbg.generated
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.label
     *
     * @return the value of liv_product.label
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.label
     *
     * @param label the value for liv_product.label
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.create_time
     *
     * @return the value of liv_product.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.create_time
     *
     * @param createTime the value for liv_product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.create_person
     *
     * @return the value of liv_product.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.create_person
     *
     * @param createPerson the value for liv_product.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.update_time
     *
     * @return the value of liv_product.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.update_time
     *
     * @param updateTime the value for liv_product.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liv_product.update_person
     *
     * @return the value of liv_product.update_person
     *
     * @mbg.generated
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liv_product.update_person
     *
     * @param updatePerson the value for liv_product.update_person
     *
     * @mbg.generated
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getThumb() == null ? other.getThumb() == null : this.getThumb().equals(other.getThumb()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getBrandName() == null ? other.getBrandName() == null : this.getBrandName().equals(other.getBrandName()))
            && (this.getKeywords() == null ? other.getKeywords() == null : this.getKeywords().equals(other.getKeywords()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getSalePrice() == null ? other.getSalePrice() == null : this.getSalePrice().equals(other.getSalePrice()))
            && (this.getClearPrice() == null ? other.getClearPrice() == null : this.getClearPrice().equals(other.getClearPrice()))
            && (this.getMarketPrice() == null ? other.getMarketPrice() == null : this.getMarketPrice().equals(other.getMarketPrice()))
            && (this.getVendor() == null ? other.getVendor() == null : this.getVendor().equals(other.getVendor()))
            && (this.getIsBest() == null ? other.getIsBest() == null : this.getIsBest().equals(other.getIsBest()))
            && (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getLabel() == null ? other.getLabel() == null : this.getLabel().equals(other.getLabel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getThumb() == null) ? 0 : getThumb().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getBrandName() == null) ? 0 : getBrandName().hashCode());
        result = prime * result + ((getKeywords() == null) ? 0 : getKeywords().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getSalePrice() == null) ? 0 : getSalePrice().hashCode());
        result = prime * result + ((getClearPrice() == null) ? 0 : getClearPrice().hashCode());
        result = prime * result + ((getMarketPrice() == null) ? 0 : getMarketPrice().hashCode());
        result = prime * result + ((getVendor() == null) ? 0 : getVendor().hashCode());
        result = prime * result + ((getIsBest() == null) ? 0 : getIsBest().hashCode());
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getLabel() == null) ? 0 : getLabel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liv_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", thumb=").append(thumb);
        sb.append(", currency=").append(currency);
        sb.append(", brandName=").append(brandName);
        sb.append(", keywords=").append(keywords);
        sb.append(", description=").append(description);
        sb.append(", salePrice=").append(salePrice);
        sb.append(", clearPrice=").append(clearPrice);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", vendor=").append(vendor);
        sb.append(", isBest=").append(isBest);
        sb.append(", hotelId=").append(hotelId);
        sb.append(", label=").append(label);
        sb.append(", createTime=").append(createTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append("]");
        return sb.toString();
    }
}